spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
        show_sql: true
  datasource:
    username: root
    password: Ltkmaby12
    url: jdbc:mysql://:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
server:
  port: 8080

indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: Playback
    - url: http://www.topazelectro.ru/
      name: Топаз-сервис